<a href="https://colab.research.google.com/github/SANGMISKAR/data_test_on_colab/blob/main/sanket_dsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


date 04/07/2025


In [ ]:
# two dim array
myarr = np.array([[[1,2,3,4,5],[11,22,33,44,55],[55,88,44,5,99,55,100]]])
print(myarr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

In [ ]:
import numpy as np
myarr = np.array([10,22,33,44,55])
print(myarr)


print(myarr[2])

[10 22 33 44 55]
33


In [ ]:
# two dim array
myarr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(myarr)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


import numpy as np

. three dim array
myarr_3d = np.array([[[1, 2, 3,4, 5, 6]], [[7, 8, 9, 10, 11, 12]], [[17, 18, 19, 101, 111, 122]]])
print(myarr_3d)

print(myarr_3d[1,2])

In [ ]:
myarr_3d = np.array([[[1, 2, 3,4, 5, 6]], [[7, 8, 9, 10, 11, 12]], [[17, 18, 19, 101, 111, 122]]])
print(myarr_3d)


[[[  1   2   3   4   5   6]]

 [[  7   8   9  10  11  12]]

 [[ 17  18  19 101 111 122]]]


In [ ]:
print (myarr_3d.shape)

(3, 1, 6)
